<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title ?? 'Report' }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #eee;
        }
        
        .academy-info {
            margin-bottom: 10px;
        }
        
        .academy-name {
            font-size: 24px;
            font-weight: bold;
            color: #2563eb;
            margin-bottom: 5px;
        }
        
        .report-title {
            font-size: 20px;
            font-weight: bold;
            margin: 15px 0;
            color: #1f2937;
        }
        
        .report-meta {
            font-size: 12px;
            color: #6b7280;
            margin-top: 10px;
        }
        
        .content {
            margin: 20px 0;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            font-size: 14px;
        }
        
        th, td {
            border: 1px solid #ddd;
            padding: 12px 8px;
            text-align: left;
        }
        
        th {
            background-color: #f8f9fa;
            font-weight: bold;
            color: #374151;
        }
        
        tr:nth-child(even) {
            background-color: #f9fafb;
        }
        
        .section {
            margin: 30px 0;
        }
        
        .section-title {
            font-size: 16px;
            font-weight: bold;
            margin-bottom: 15px;
            color: #1f2937;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 5px;
        }
        
        .badge {
            display: inline-block;
            padding: 2px 8px;
            background-color: #e5e7eb;
            color: #374151;
            border-radius: 12px;
            font-size: 12px;
            margin-right: 5px;
        }
        
        .badge-primary {
            background-color: #dbeafe;
            color: #1d4ed8;
        }
        
        .badge-success {
            background-color: #d1fae5;
            color: #065f46;
        }
        
        .badge-warning {
            background-color: #fef3c7;
            color: #92400e;
        }
        
        .badge-danger {
            background-color: #fee2e2;
            color: #dc2626;
        }
        
        .footer {
            position: fixed;
            bottom: 20px;
            right: 20px;
            font-size: 10px;
            color: #9ca3af;
        }
        
        .page-break {
            page-break-after: always;
        }
        
        @media print {
            body {
                padding: 15px;
            }
            
            .footer {
                position: fixed;
                bottom: 10px;
                right: 10px;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="academy-info">
            <div class="academy-name">{{ $academy->name ?? 'Academy' }}</div>
            @if(isset($academy->address))
                <div style="font-size: 12px; color: #6b7280;">{{ $academy->address }}</div>
            @endif
            @if(isset($academy->phone))
                <div style="font-size: 12px; color: #6b7280;">Phone: {{ $academy->phone }}</div>
            @endif
            @if(isset($academy->email))
                <div style="font-size: 12px; color: #6b7280;">Email: {{ $academy->email }}</div>
            @endif
        </div>
        
        <div class="report-title">{{ $title }}</div>
        
        <div class="report-meta">
            Generated by: {{ $generatedBy }} | Date: {{ $generatedAt }}
        </div>
    </div>

    <div class="content">
        @yield('content')
    </div>

    <div class="footer">
        International Sports Solutions - Print Report
    </div>
</body>
</html>
