name: Build & Deploy via FTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Build Front-end Assets
      run: |
        npm ci
        npm run build

    - name: FTP Upload
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.internationalsportssolutions.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: / # The FTP user sports_admin is already jailed to sports_admin/
        exclude: |
          **/.git*
          **/node_modules/**
          **/tests/**
